twist_mux:
  ros_parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      key:
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 100
